version: '3'

services:
  gpt-music:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    ports:
      - 8000:8000
